/*
 *This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.List;
import java.util.Scanner;

public class Main {
    
	//static Scanner teclado = new Scanner(System.in);
	
    public static void main (String [] args) {
    	
    	ArrayList<Libro> catalogo = new ArrayList<Libro>();
    	
    	while(true) {
    		int opcion = menu();
    		switch (opcion) {
			case 1:
				//TODO Alta de Libro
				//titulo:isbn:genero:autor:paginas
				alta(catalogo);
				break;
			case 2:
				//TODO Lista de Libros
				listaLibro(catalogo);
				break;
			case 3:
				break;
			case 4:
				break;
			case 5:
				break;
			case 6:
				System.out.println("\nHasta la proxima.");
				break;
			default:
				break;
			
			}
    		
    		if (opcion == 6) {
				break;
			}
    	}
    }
    
    private static int menu() {
    	int opcion=0;
    	
    	do {
    		System.out.println("\nOpciones: \n");
    		System.out.println("\t1. Alta de Libro.");
    		System.out.println("\t2. Lista de Libros.");
    		System.out.println("\t3. Baja de Libros.");
    		System.out.println("\t4. Búsqueda de Libros.");
    		System.out.println("\t5. Ordenacion de Libros.");
    		System.out.println("\t6. Salida.\n");
    		System.out.println("\tIntroduce la opcion: \n");
    	
    		opcion = leerOpcion(6);
    		
    	}while(opcion <=0);
    	
    	return opcion;
    }
    
    private static int leerOpcion(int max) {
    	int opcion = -1;
    	try {
    		Scanner teclado = new Scanner(System.in);
    		opcion=teclado.nextInt();
    		if(opcion>max)
    			opcion=-1;
    	}catch (InputMismatchException e) {
			System.out.println("Opción incorrecta");
		}
    	
    	return opcion;
    }
    
    private static void alta(ArrayList<Libro> catalogo) {
    	//Leer de la entrada
    	String datosLibro = obtenerDatosLibro();
    	//titulo:isbn:genero:autor:paginas
    	//Procesar la entrada
    	Libro libro = procesaEntrada(datosLibro);
    	//Crear el libro con los datos de la entrada
    	catalogo.add(libro);
    	//Meter el libro en el catalogo
    }
    
    private static String obtenerDatosLibro() {
    	String datos=null;
    	
    	boolean validado=false;
    	while(!validado) {
    		System.out.println("\nIntroduce los datos de un libro.");
    		System.out.println("Usa el formato \"titulo:isbn:genero:autor:paginas\"\n");
    		
    		try {
    			datos = leerCadena();
    			if(true)//Supongo de momento que valida siempre
    				validado=true;
    		}catch (InputMismatchException e) {
				System.out.println("Datos de entrada no válidos");
			}
    		    		
    	}
    	
    	return datos;
    }
    
    private static Libro procesaEntrada(String entrada) {
    	Libro libro = null;
    	
    	String [] datos = entrada.split(":");
    	
    	String titulo = datos[0];
    	String isbn = datos[1];
    	Genero genero = Genero.getGenero(datos[2]);
    	String autor = datos[3];
    	Integer paginas = Integer.parseInt(datos[4]);
    	
    	libro = new Libro(titulo,isbn,genero,autor,paginas);
    	
    	return libro;
    }
    
    private static String leerCadena() {
    	String opcion = null;
    	Scanner teclado = new Scanner(System.in);
        opcion=teclado.nextLine();
    	return opcion;
    }
    
    private static void listaLibro(ArrayList<Libro> catalogo) {
    	
    	
    	
    	for (int i = 0; i < catalogo.size(); i++) {
    	      Libro libro = catalogo.get(i);
    	      System.out.println("\nLos datos del libro " + (i+1) + " son:\n");
    	      System.out.println("\t1.- " + libro.getTitulo() + ".\n" + "\t2.- " + libro.getIsbn() +
    	    		  ".\n" + "\t3.- " + libro.getGenero() + ".\n" + "\t4.- " + libro.getAutor() +
    	    		  ".\n" + "\t5.- " + libro.getPaginas() + ".\n");
    	}
    } 
}
